### ISSUE TITLE
Site Characterization

### ISSUE THREAD

**Issue by ElectricGr** [MOJN-Veg/mojn-iu-rpackage#12]
-We never discussed this portion of IU, site characterization/evaluation. This will be necessary for PARA and DEVA. None of the fields for this portion of IU have a place in the forms we already discussed
[SiteCharac.pdf](https://github.com/MOJN-Veg/mojn-iu-rpackage/files/8445392/SiteCharac.pdf)
.

**Comment by HarpoMark** [comment]
Site Characterization is now being handled in RECON.

Site Establishment includes the permanent characteristics of a plot that are collected during site installation/first monitoring.

Upslope Percent and Transect Bearing will be stored in the Site table
PointType, Location on Transect and Notes will be stored for each piece of rebar in the Rebar spatial table.
