### ISSUE TITLE
Plot Establishment

### ISSUE THREAD

**Issue by ElectricGr** [MOJN-Veg/mojn-iu-rpackage#13]
Some of this can be stored in the spatial data, but there are a number of fields that are not accounted for in our current plans for the SOP forms. Additional fields that currently don't have a place include, Direction to parking, Direction from vehicle to plot, general location notes, slope, and bearings
[SiteEstablish.pdf](https://github.com/MOJN-Veg/mojn-iu-rpackage/files/8445394/SiteEstablish.pdf)
.

**Comment by wright13** [comment]
@HarpoMark included these fields in a form called Site Manager which handles all site-level info. Site characterization info like rejections and shifts is currently being stored in the GRTS layer in AGOL and can be edited/entered through Field Maps. Does that sound reasonable @ElectricGr?
